# docker-compose.yml
services:
  echidna:
    build:
      context: .
      dockerfile: Dockerfile.echidna
    container_name: daedaluzz-echidna
    volumes:
      - ./results:/daedaluzz/generated-mazes/results
    environment:
      TASK: "1"
      TIME_LIMIT: "100"
      MAZE_NUMBER: "4"
      SEED: ""
    entrypoint: >
      bash -c "./run-echidna.sh $${TASK} $${TIME_LIMIT} $${MAZE_NUMBER} $${SEED}"

  foundry:
    build:
      context: .
      dockerfile: Dockerfile.foundry
    container_name: daedaluzz-foundry
    volumes:
      - ./results:/daedaluzz/generated-mazes/results
    environment:
      TASK: "1"
      TIME_LIMIT: "100"
      MAZE_NUMBER: "4"
      SEED: ""
    entrypoint: >
      bash -c ./run-foundry.sh $${TASK} $${TIME_LIMIT} $${MAZE_NUMBER} $${SEED}

  ityfuzz:
    build:
      context: .
      dockerfile: Dockerfile.ityfuzz
    container_name: daedaluzz-ityfuzz
    volumes:
      - ./results:/daedaluzz/generated-mazes/results
    environment:
      TASK: "1"
      TIME_LIMIT: "100"
      MAZE_NUMBER: "4"
      SEED: ""
    entrypoint: >
      bash -c ./run-ityfuzz.sh $${TASK} $${TIME_LIMIT} $${MAZE_NUMBER} $${SEED}

  reports:
    build:
      context: .
      dockerfile: Dockerfile.reports
    container_name: daedaluzz-reports
    volumes:
      - ./results:/data
    command: ["/data"]
